alkemyTech/OT249-Server

src/main/java/com/alkemy/ong/model/Activity.java, src/main/java/com/alkemy/ong/repository/ActivityRepository.java, src/main/resources/application.properties
OT249-21. Activity Entity created
=> OT249-21. Activity Entity created

pom.xml, src/main/java/com/alkemy/ong/controller/LoginController.java, src/main/java/com/alkemy/ong/dtos/LoginRequestDTO.java, src/main/java/com/alkemy/ong/repository/UserRepository.java, src/main/java/com/alkemy/ong/security/ApiSecurityConfig.java, src/main/java/com/alkemy/ong/service/LoginService.java, src/main/java/com/alkemy/ong/service/LoginServiceImpl.java
=> OT249-25: Endpoint de autenticación

src/main/java/com/alkemy/ong/repository/NewsRepository.java, src/main/java/com/alkemy/ong/service/NewsService.java, src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
=> OT249-19: Fixing News Id Issues

src/main/java/com/alkemy/ong/controller/UserController.java, src/main/java/com/alkemy/ong/dto/UserDto.java, src/main/java/com/alkemy/ong/exceptions/UserControllerEx.java, src/main/java/com/alkemy/ong/model/User.java
Creacion de endpoint de registro de usuarios
=> Subiendo al repo la tarea OT-249-24 y solucion del fix de la entidad user

pom.xml
Se agregó la dependencia Sendgrid al POM
=> OT249-27: integrar envio emails

src/main/java/com/alkemy/ong/model/Member.java, src/main/java/com/alkemy/ong/repository/MemberRepository.java, src/main/java/com/alkemy/ong/service/IMemberService.java, src/main/java/com/alkemy/ong/service/MemberServiceImpl.java
fixed member class and repository
=> OT249-22 - Crear modelo y repositorio base de Members

src/main/java/com/alkemy/ong/model/User.java
Añadiendo Lombok a la entidad User
=> Fix ot249 17

pom.xml, src/main/java/com/alkemy/ong/config/ModelMapperConfig.java
=> OT249-modelMapper dependency

src/main/java/com/alkemy/ong/model/Role.java, src/main/java/com/alkemy/ong/repository/RoleRepository.java, src/main/java/com/alkemy/ong/service/IRoleService.java, src/main/java/com/alkemy/ong/service/RoleServiceImpl.java
fixed class and role repository using uuid
=> OT249-16 - Crear modelo y repositorio base de Roles

src/main/java/com/alkemy/ong/Utils/PageUtils.java, src/main/java/com/alkemy/ong/controller/UserController.java, src/main/java/com/alkemy/ong/repository/UserRepository.java, src/main/java/com/alkemy/ong/service/UserService.java, src/main/java/com/alkemy/ong/service/UserServiceImpl.java
=> OT249-35: Endpoint para listar Usuarios

src/main/java/com/alkemy/ong/controller/CategoryController.java, src/main/java/com/alkemy/ong/dto/CategoryDto.java, src/main/java/com/alkemy/ong/repository/CategoryRepository.java, src/main/java/com/alkemy/ong/service/CategoryService.java, src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
=> OT249-40 - Endpoint Listado de Categorías

src/main/java/com/alkemy/ong/controller/NewController.java, src/main/java/com/alkemy/ong/dto/NewDTO.java
Controlador y DTO de "New" para realizar Merge, así todos trabajamos sobre los mismas clases.
=> OT249-45. New Controller and DTO added.

src/main/java/com/alkemy/ong/model/News.java, src/main/java/com/alkemy/ong/repository/NewsRepository.java, src/main/java/com/alkemy/ong/service/NewsService.java, src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
Migrate ID String type to UUID type.
=> OT249-19: Migration News' Model ID to UUID.

src/main/java/com/alkemy/ong/controller/CategoryController.java, src/main/java/com/alkemy/ong/controller/UserController.java, src/main/java/com/alkemy/ong/dto/CategoryDto.java, src/main/java/com/alkemy/ong/model/Role.java, src/main/java/com/alkemy/ong/model/User.java, src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java, src/main/java/com/alkemy/ong/service/RoleServiceImpl.java, src/main/java/com/alkemy/ong/service/UserService.java, src/main/java/com/alkemy/ong/service/UserServiceImpl.java
=> Subiendo al repositorio tarea de delete user

pom.xml, src/main/java/com/alkemy/ong/controller/BucketController.java, src/main/java/com/alkemy/ong/service/AmazonClient.java, src/main/resources/application.properties
Deben agregar las siguientes variabkes de entorno:
-ENDPOINT_URL
-BUCKET_NAME
-ACCESS_KEY
-SECRET-KEY
=> OT249-38 Amazon S3

src/main/resources/application.properties
=> OT249-Rollback App Properties.

src/main/java/com/alkemy/ong/controller/TestimonialController.java, src/main/java/com/alkemy/ong/dto/TestimonialDto.java, src/main/java/com/alkemy/ong/model/Testimonial.java, src/main/java/com/alkemy/ong/service/TestimonialService.java, src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
=> OT249-65: Endpoint Creación Testimonios

src/main/java/com/alkemy/ong/controller/TestimonialController.java, src/main/java/com/alkemy/ong/service/TestimonialService.java, src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
=> OT249-67: Endpoint eliminación de Testimonios

src/main/java/com/alkemy/ong/model/Testimonial.java
=> OT249-67: Added delete SQL Annotation

src/main/java/com/alkemy/ong/model/Contact.java, src/main/java/com/alkemy/ong/repository/ContactRepository.java, src/main/java/com/alkemy/ong/service/ContactService.java, src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java
Se crearon las capas de contact, solo faltaria el controlador .
Creacion de contacto.
=> OT249-53 Contact 

src/main/java/com/alkemy/ong/controller/SlideController.java, src/main/java/com/alkemy/ong/dto/SlideDto.java, src/main/java/com/alkemy/ong/service/SlideService.java, src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
=> OT249-55-endpoint-listar-slides

src/main/java/com/alkemy/ong/controller/UserController.java, src/main/java/com/alkemy/ong/service/UserService.java, src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
Summary:
- UserController
- User Service and implements
=> OT249-36. Added endpoint Get details Authenticated User. 

src/main/java/com/alkemy/ong/controller/SlideController.java, src/main/java/com/alkemy/ong/dto/SlideDetailsDto.java, src/main/java/com/alkemy/ong/service/SlideService.java, src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
=> Ot249 56 endpoint slide details

src/main/java/com/alkemy/ong/controller/ContactController.java, src/main/java/com/alkemy/ong/dto/ContactDto.java, src/main/java/com/alkemy/ong/model/Contact.java, src/main/java/com/alkemy/ong/service/ContactService.java, src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java
=> OT249-53 Save contacts

src/main/java/com/alkemy/ong/dto/ContactDto.java, src/main/java/com/alkemy/ong/model/Contact.java
Cambie el tipado del atributo phone a String.
=> OT249-53 HOT FIX

src/main/java/com/alkemy/ong/controller/TestimonialController.java, src/main/java/com/alkemy/ong/exceptions/CustomExceptionController.java, src/main/java/com/alkemy/ong/model/Testimonial.java, src/main/java/com/alkemy/ong/service/TestimonialService.java, src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
=> OT249-67: Fixed Deletion process

src/main/java/com/alkemy/ong/controller/SlideController.java, src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
=> OT249-59. Slides Delete controller and service.

src/main/java/com/alkemy/ong/controller/CategoryController.java, src/main/java/com/alkemy/ong/service/CategoryService.java, src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
=> OT249-43 : Endpoint Actualización Categorías

src/main/java/com/alkemy/ong/controller/MemberController.java, src/main/java/com/alkemy/ong/dto/MemberDto.java, src/main/java/com/alkemy/ong/model/Member.java, src/main/java/com/alkemy/ong/service/IMemberService.java, src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
=> OT249-69 : Endpoint Creación Miembros

src/main/java/com/alkemy/ong/controller/ActivityController.java, src/main/java/com/alkemy/ong/dto/ActivityDto.java, src/main/java/com/alkemy/ong/service/ActivityService.java, src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java
Endpoint creación de actividades
=> OT249 endpoint creacion de actividades

src/main/java/com/alkemy/ong/controller/MemberController.java, src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
=> OT249-70 : Endpoint Eliminación Miembros

src/main/java/com/alkemy/ong/controller/MemberController.java, src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
=> OT249-68 : Endpoint para listar Miembros

src/main/java/com/alkemy/ong/controller/NewController.java
=> OT249-47: Fixed RBA.

src/main/java/com/alkemy/ong/dto/UserDto.java
=> OT249-35: Added Ignored fields.

pom.xml, src/main/java/com/alkemy/ong/OngApplication.java, src/main/java/com/alkemy/ong/config/SwaggerConfiguration.java, src/main/java/com/alkemy/ong/controller/ActivityController.java, src/main/java/com/alkemy/ong/controller/BucketController.java, src/main/java/com/alkemy/ong/controller/ContactController.java, src/main/java/com/alkemy/ong/controller/OrgController.java, src/main/java/com/alkemy/ong/controller/SlideController.java, src/main/java/com/alkemy/ong/controller/SwaggerController.java, src/main/java/com/alkemy/ong/security/ApiSecurityConfig.java
Add documentation with Swagger
=> OT249-84 : Agregar documentación con Swagger 

src/main/java/com/alkemy/ong/Utils/ActivitySeedData.java
=> OT249-52 Seed data de actividades

src/main/java/com/alkemy/ong/Utils/PageUtils.java, src/main/java/com/alkemy/ong/controller/MemberController.java, src/main/java/com/alkemy/ong/dto/PageDto.java, src/main/java/com/alkemy/ong/service/IMemberService.java, src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java, src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
=> OT249-82: Agregar paginación a Miembros

src/main/java/com/alkemy/ong/controller/OrgController.java, src/main/java/com/alkemy/ong/controller/SlideController.java, src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
Summary:
- Slide upDate:
- Validation for null fields added.
- catch exception for Slide not found added.
- Slides for public organization:
- PreAuthorize changed for USER and ADMIN access.
=> OT249-58,60. Fixes.

src/main/java/com/alkemy/ong/controller/CommentController.java, src/main/java/com/alkemy/ong/service/CommentService.java, src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
Endpoint de actualizacion de comentarios
=> Endpoint de actualizacion de comentarios

src/main/java/com/alkemy/ong/controller/CommentController.java, src/main/java/com/alkemy/ong/service/CommentService.java, src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
Ot249 78 eliminacion de comentarios
=> Ot249 78 eliminacion de comentarios

src/main/java/com/alkemy/ong/controller/TestimonialController.java, src/main/java/com/alkemy/ong/service/TestimonialService.java, src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
Add Pagination to Testimonials
=> OT249-83 : Agregar paginación a Testimonios

src/main/java/com/alkemy/ong/controller/CategoryController.java
Add documentation to Categories
=> OT249-85 : Agregar documentación a Categorías

lombok.config, pom.xml
=> OT249-101: Fixed Excludes classes and packages.

src/main/java/com/alkemy/ong/controller/NewController.java, src/test/java/com/alkemy/ong/controller/NewControllerTest.java, src/test/java/com/alkemy/ong/service/impl/NewsServiceImplTest.java
=> OT249-93: Test: Endpoints /news 

src/test/java/com/alkemy/ong/controller/TestimonialControllerTest.java, src/test/java/com/alkemy/ong/service/impl/TestimonialServiceImplTest.java
=> OT249-98: Test: Endpoints /testimonials
